name: Markdown Lint Check on Push

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Markdown Linting Action
        uses: avto-dev/markdown-lint@v1.4.0
        with:
          args: '**/*.md'