name: Markdown Lint Check on Pull Request

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1.0.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - name: Install markdownlint-cli
        run: npm install markdownlint-cli
      - name: Run markdownlint-cli
        run: $(npm bin)/markdownlint **/*.md --ignore node_modules | reviewdog -efm="%f:%l %m" -name="markdownlint" -diff="git diff HEAD" -reporter=github-pr-review -tee | reviewdog -efm="%f:%l:%c %m" -name="markdownlint" -diff="git diff HEAD" -reporter=github-pr-review -tee
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
