name: Text Lint Check on Push

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1.0.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - name: Install NPM Packages
        run: npm install
      - name: Run textlint
        run: $(npm bin)/textlint -c .textlintrc **
